"""Export scraped position DataFrames to CSV and SQL without touching the DB.

DataFrames use the canonical Chinese column layout (see ingest._POS_MAPPING).
The SQL export mirrors ingest.ingest_positions_df: rows are enriched with
normalized fields, content_hash is computed the same way, and inserts use
ON CONFLICT (content_hash) DO NOTHING so they are safe to replay.
"""
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
from ingest import _POS_MAPPING, _compute_hash, _enrich_record, _row_to_record

_SQL_COLUMNS = [
    "year", "job_type", "exam_type", "employer", "position_example",
    "edu_requirement", "edu_level_norm", "undergrad_major", "grad_major",
    "exam_form", "signup_time", "exam_time", "special_requirements",
    "work_location", "location_tags", "source_url", "notes", "raw_major",
    "content_hash",
]


def df_to_records(df: pd.DataFrame, default_year=2026):
    records = []
    for _, row in df.iterrows():
        rec = _row_to_record(row, _POS_MAPPING, default_year)
        if not rec.get("exam_type") and not rec.get("position_example"):
            continue
        rec = _enrich_record(rec)
        rec["content_hash"] = _compute_hash(rec)
        records.append(rec)
    return records


def _sql_literal(val):
    if val is None:
        return "NULL"
    if isinstance(val, int):
        return str(val)
    if isinstance(val, list):
        if not val:
            return "NULL"
        inner = ",".join('"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"' for v in val)
        return "'{" + inner.replace("'", "''") + "}'"
    return "'" + str(val).replace("'", "''") + "'"


def export_csv_sql(df: pd.DataFrame, out_prefix: str, default_year=2026, batch=500):
    """Write <out_prefix>.csv and <out_prefix>.sql; returns record count."""
    os.makedirs(os.path.dirname(out_prefix) or ".", exist_ok=True)
    df.to_csv(out_prefix + ".csv", index=False, encoding="utf-8-sig")

    records = df_to_records(df, default_year=default_year)
    # de-dup within the export on content_hash
    seen = set()
    unique = []
    for rec in records:
        if rec["content_hash"] in seen:
            continue
        seen.add(rec["content_hash"])
        unique.append(rec)

    with open(out_prefix + ".sql", "w", encoding="utf-8") as f:
        f.write("-- Generated by export_utils.export_csv_sql; safe to replay (ON CONFLICT DO NOTHING)\n")
        f.write("BEGIN;\n")
        for i in range(0, len(unique), batch):
            chunk = unique[i:i + batch]
            f.write(f"INSERT INTO positions ({', '.join(_SQL_COLUMNS)}) VALUES\n")
            rows = []
            for rec in chunk:
                vals = ", ".join(_sql_literal(rec.get(col)) for col in _SQL_COLUMNS)
                rows.append(f"({vals})")
            f.write(",\n".join(rows))
            f.write("\nON CONFLICT (content_hash) DO NOTHING;\n")
        f.write("COMMIT;\n")
    return len(unique)
